name: films
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:

  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  go_router: ^13.0.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  sqflite: ^2.3.1
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.8
  derry: ^1.5.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  very_good_analysis: ^5.0.0+1

flutter:

  uses-material-design: true

scripts:
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  watch: flutter packages pub run build_runner watch --delete-conflicting-outputs
  clean: flutter packages pub run build_runner clean build
  get: flutter pub get
  upgrade: flutter pub upgrade --major-versions